name: Deploy to Vercel

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name (could be 'master')

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # If you need to build your site
      # - name: Build
      #   run: |
      #     npm ci
      #     npm run build
      
      # Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # You'll need to add this in GitHub secrets
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # You'll need to add this in GitHub secrets
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # You'll need to add this in GitHub secrets
          vercel-args: '--prod'  # Deploy to production
